# Generated by Django 4.2.29 on 2026-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_height', models.FloatField()),
                ('max_height', models.FloatField()),
                ('min_width', models.FloatField()),
                ('max_width', models.FloatField()),
                ('min_size', models.FloatField()),
                ('max_size', models.FloatField()),
                ('is_jpg', models.BooleanField()),
                ('is_png', models.BooleanField()),
                ('is_jpeg', models.BooleanField(default=True)),
                ('bgcolor_threshold', models.FloatField(default=40)),
                ('bg_uniformity_threshold', models.FloatField(default=35)),
                ('blurness_threshold', models.FloatField(default=100)),
                ('greyness_threshold', models.FloatField(default=15)),
                ('symmetry_threshold', models.FloatField(default=30)),
                ('min_head_percent', models.FloatField(default=10)),
                ('max_head_percent', models.FloatField(default=80)),
                ('bypass_height_check', models.BooleanField(default=False)),
                ('bypass_width_check', models.BooleanField(default=False)),
                ('bypass_size_check', models.BooleanField(default=False)),
                ('bypass_format_check', models.BooleanField(default=False)),
                ('bypass_background_check', models.BooleanField(default=False)),
                ('bypass_blurness_check', models.BooleanField(default=False)),
                ('bypass_greyness_check', models.BooleanField(default=False)),
                ('bypass_symmetry_check', models.BooleanField(default=False)),
                ('bypass_head_check', models.BooleanField(default=False)),
                ('bypass_eye_check', models.BooleanField(default=False)),
                ('bypass_corrupted_check', models.BooleanField(default=False)),
                ('noise_threshold', models.FloatField(default=25)),
                ('dust_spot_threshold', models.IntegerField(default=15)),
                ('text_region_threshold', models.IntegerField(default=8)),
                ('bypass_printed_photo_check', models.BooleanField(default=False)),
                ('bypass_dust_noise_check', models.BooleanField(default=False)),
                ('bypass_text_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.FileField(upload_to='photo_folder/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
