# Generated by Django 4.2.4 on 2025-08-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_default_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='bgcolor_threshold',
            field=models.FloatField(default=40),
        ),
        migrations.AlterField(
            model_name='config',
            name='blurness_threshold',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='config',
            name='greyness_threshold',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='config',
            name='pixelated_threshold',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='symmetry_threshold',
            field=models.FloatField(default=35),
        ),
    ]
