# Generated by Django 5.2.5 on 2025-08-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_config_bgcolor_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='bg_uniformity_threshold',
            field=models.FloatField(default=25),
        ),
    ]
